### PR TITLE
Create LongestCommonSubsequence.java

### PR DESCRIPTION
**Pull request by nik132-eng**
Recursive call for longest common subsequence method

### CODE REVIEW

**Comment by nik132-eng** [comment]
I am new to Github and open source can you help with what to do. Is there any mistake in the code?

**Comment by aniruddhabagal** [comment]
Hello, Yeah the code is fine. But can you create a folder named Recursion and commit this file into that folder. And then maybe create a pr.
Also pls give a proper file name so that people can understand.

**Comment by nik132-eng** [comment]
Now is this Fine?

**Comment by aniruddhabagal** [comment]
No, name the folder as "Recursion" and the file name inside it as "LongestCommonSubsequence.java"

**Comment by aniruddhabagal** [comment]
Now the pull request  #9 is opened similar to this. So closing this and approve the other one.

**Pull request closed without merging**
